### ISSUE TITLE
rake build failing with RangeError

### ISSUE THREAD

**Issue by kevgathuku** [yorobot/football.db#5]
Hello,
When trying to build the initial database with the `rake build` command, I am getting the following error:

``` shell
** Invoke importworld (first_time)
** Invoke configworld (first_time)
** Invoke config (first_time)
** Invoke env 
** Execute config
[warn] Rakefile - 2015-02-02 17:43:00 +0300
rake aborted!
RangeError: 69936435566960 is out of range for ActiveRecord::Type::Integer with limit 4
```

I suspect that it could be happening in 

``` ruby
## log all warns, errors, fatals to db
  LogDb.setup
```

but I could be wrong.

How should I deal with this?
Thanks in advance.

**Comment by geraldb** [comment]
Thanks for reporting. What database are you using? e.g. SQlite, MySQL, PostgreSQL etc.?

**Comment by kevgathuku** [comment]
@geraldb I am using sqlite. I have not modified the default settings. 
However when I changed the tid field to add a limit of 8, the build command ran successfully

**Comment by geraldb** [comment]
Thanks. Good catch. Cheers.

**Comment by kevgathuku** [comment]
@geraldb I think this is really an issue with https://github.com/rubylibs/logutils-activerecord
so I'll close this.
Would you mind looking at the [Pull Request](https://github.com/rubylibs/logutils-activerecord/pull/1) I submitted there and give me your views?
Thanks.
